# Site settings
title: The ALMANAC Lab
email:
description: The ALMANAC Lab project 
url: http://http://almanacproject.github.io/

# contact parameters
github_site: https://github.com/almanacproject
contact: http://www.almanac-project.eu/contact.php

